// lib/blogData.ts

export interface BlogPostContentSection {
  heading: string;
  paragraph: string;
}
export interface BlogPostContent {
  introduction: string;
  sections: BlogPostContentSection[];
  conclusion: string;
}

export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  date: string;
  imageUrl: string;
  imageAlt: string;
  imageHint?: string;
  content: BlogPostContent;
  tags?: string[];
}

export const mockBlogPosts: BlogPost[] = [
  {
    slug: 'future-of-sports-tech-2024',
    title: 'The Future of Sports Tech: Trends to Watch in 2024',
    excerpt: 'Explore the cutting-edge technologies and innovations set to redefine the sports industry in the coming year and beyond.',
    date: '2024-01-15',
    imageUrl: 'https://placehold.co/1200x630.png',
    imageAlt: 'Futuristic sports technology graphic',
    imageHint: 'sports technology',
    tags: ['Sports Tech', 'Innovation', 'Future Trends'],
    content: {
      introduction: "The sports technology landscape is evolving at an unprecedented pace. As we step into 2024, several key trends are emerging that promise to transform how athletes train, teams strategize, and fans engage with sports. From AI-driven analytics to immersive viewing experiences, the future is exciting.",
      sections: [
        {
          heading: "AI and Machine Learning",
          paragraph: "Artificial intelligence is becoming deeply integrated into sports. Expect more sophisticated player performance analytics, personalized training regimens generated by AI, and AI-powered scouting tools that can identify talent with greater accuracy. Game strategy will also be heavily influenced by AI's ability to process vast amounts of data and predict opponent moves."
        },
        {
          heading: "Wearable Technology Advancements",
          paragraph: "Wearables are moving beyond basic fitness tracking. Next-generation devices will offer more precise biomechanical data, real-time injury risk assessment, and even mental state monitoring. This data will be crucial for optimizing performance and ensuring athlete well-being."
        },
        {
          heading: "Immersive Fan Experiences",
          paragraph: "Virtual Reality (VR) and Augmented Reality (AR) are set to revolutionize how fans experience sports. Imagine watching a game from a player's perspective through VR, or using AR to see real-time stats overlaid on the field while at the stadium. These technologies will create deeper engagement and open new revenue streams."
        }
      ],
      conclusion: "The fusion of sports and technology is creating a new era of possibilities. As these trends mature, Rally Athletes is committed to being at the forefront, developing solutions that harness these advancements to empower everyone in the sports ecosystem."
    }
  },
  {
    slug: 'maximizing-athlete-potential',
    title: 'Maximizing Athlete Potential with My Team Dashboard',
    excerpt: 'Discover how My Team Dashboard empowers coaches and athletes to unlock peak performance through streamlined communication and data insights.',
    date: '2024-02-10',
    imageUrl: 'https://placehold.co/1200x630.png',
    imageAlt: 'Dashboard interface showing athlete stats',
    imageHint: 'dashboard analytics',
    tags: ['My Team Dashboard', 'Coaching', 'Performance'],
    content: {
      introduction: "My Team Dashboard is more than just a management tool; it's a catalyst for growth. By providing coaches and athletes with a centralized platform for communication, scheduling, and performance analysis, we're helping teams unlock their true potential.",
      sections: [
        {
          heading: "Streamlined Communication",
          paragraph: "Effective communication is the backbone of any successful team. My Team Dashboard offers secure messaging, announcement boards, and shared calendars, ensuring everyone stays informed and connected, whether on or off the field."
        },
        {
          heading: "Data-Driven Performance Insights",
          paragraph: "Track key performance indicators, monitor training loads, and visualize progress with our intuitive analytics tools. Coaches can make informed decisions, and athletes can understand their strengths and areas for improvement, leading to more targeted and effective training."
        },
        {
          heading: "Efficient Organization",
          paragraph: "From managing rosters and schedules to sharing training materials and game footage, My Team Dashboard simplifies administrative tasks. This allows coaches to spend less time on logistics and more time focusing on what matters most: developing their athletes."
        }
      ],
      conclusion: "Empower your team with My Team Dashboard and experience a new level of organization, communication, and performance. Rally Athletes is proud to offer this solution to help teams achieve their goals."
    }
  },
  {
    slug: 'fuel-my-game-nutrition',
    title: 'Fuel My Game: Nutrition Strategies for Peak Performance',
    excerpt: 'Learn how Fuel My Game provides personalized nutrition guidance to help athletes perform at their best and recover effectively.',
    date: '2024-03-05',
    imageUrl: 'https://placehold.co/1200x630.png',
    imageAlt: 'Healthy food and sports equipment',
    imageHint: 'healthy food sports',
    tags: ['Fuel My Game', 'Nutrition', 'Athlete Health'],
    content: {
      introduction: "Nutrition is a cornerstone of athletic performance. Fuel My Game is designed to take the guesswork out of athlete nutrition, providing personalized plans, educational resources, and tools to help athletes make informed choices that support their training and competition goals.",
      sections: [
        {
          heading: "Personalized Nutrition Plans",
          paragraph: "Every athlete is unique, and so are their nutritional needs. Fuel My Game considers factors like sport, training intensity, body composition, and individual goals to create customized meal plans and hydration strategies."
        },
        {
          heading: "Education and Resources",
          paragraph: "Knowledge is power. Our platform offers a wealth of information on sports nutrition, including articles, recipes, and expert advice. We empower athletes to understand the 'why' behind their nutritional choices."
        },
        {
          heading: "Tracking and Progress Monitoring",
          paragraph: "Athletes can log their food intake, track hydration levels, and monitor how their nutrition impacts performance and recovery. This data-driven approach helps refine strategies and ensure optimal fueling for success."
        }
      ],
      conclusion: "With Fuel My Game, athletes can confidently nourish their bodies for peak performance, faster recovery, and long-term health. Join Rally Athletes in revolutionizing how athletes approach their nutrition."
    }
  },
  {
    slug: 'scoutmesports-connecting-talent',
    title: 'ScoutMe Sports: Connecting Talent with Opportunity',
    excerpt: 'An inside look at how ScoutMe Sports is bridging the gap between aspiring athletes and professional scouting networks.',
    date: '2024-04-20',
    imageUrl: 'https://placehold.co/1200x630.png',
    imageAlt: 'Athlete performing in front of scouts',
    imageHint: 'athlete scouting',
    tags: ['ScoutMe Sports', 'Scouting', 'Athlete Recruitment'],
    content: {
      introduction: "For many talented athletes, getting noticed by scouts and securing professional opportunities can be a major hurdle. ScoutMe Sports is dedicated to breaking down these barriers, creating a transparent and efficient platform for talent discovery and recruitment.",
      sections: [
        {
          heading: "Comprehensive Athlete Profiles",
          paragraph: "Athletes can create detailed profiles showcasing their skills, achievements, academic records, and highlight videos. This provides scouts with a rich, centralized source of information to evaluate potential recruits."
        },
        {
          heading: "Advanced Scouting Tools",
          paragraph: "Scouts and organizations gain access to a powerful database of athletes, with advanced search filters and analytics to identify players اللي match their specific criteria. Our platform streamlines the scouting process, saving time and resources."
        },
        {
          heading: "Building Connections",
          paragraph: "ScoutMe Sports facilitates direct communication between athletes, coaches, and scouts, fostering a network where talent can be recognized and opportunities can flourish. We are committed to creating pathways for athletes to pursue their dreams."
        }
      ],
      conclusion: "ScoutMe Sports is leveling the playing field, ensuring that talent, hard work, and dedication are the primary drivers of an athlete's journey. Rally Athletes is proud to support this mission of connecting talent with opportunity."
    }
  }
];